import { AdminWrapper } from "../security/AdminWrapper"
import Navigation from '../components/Navigator/Navigation';
import "./app.css"
import { Toaster } from 'sonner';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AdminWrapper>
    <html lang="en">
      <body>
      <Toaster position="top-center" />
      <div><Navigation /></div>
      {children}</body>
    </html>
    </AdminWrapper>
  )
}
