import { AdminWrapper } from "../security/AdminWrapper"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AdminWrapper>
    <html lang="en">
      <body>{children}</body>
    </html>
    </AdminWrapper>
  )
}
