"use client"

import { useAuthenticator } from "@aws-amplify/ui-react";
import { Authenticator } from '@aws-amplify/ui-react';
import "@aws-amplify/ui-react/styles.css";
import { Inter } from "next/font/google";
import "./app.css";
import { View, Image, Button, Text, Heading } from "@aws-amplify/ui-react";
import { useTheme } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import './globals.css'
import GoogleAnalytics from './GoogleAnalytics'  // Add this import

import { I18n } from 'aws-amplify/utils';
import { ReactNode, useState, useEffect } from 'react';

I18n.putVocabulariesForLanguage('en', {
  'Sign In': 'Login', // Tab header
  'Sign in': 'Log in', // Button label
  'Sign in to your account': 'Welcome Back!',
  Password: 'Enter your password', // Password label
  'Forgot your password?': 'Reset Password',
  'Create Account': 'Register', // Tab header
  'Create a new account': 'New User', // Header text
  'Confirm Password': 'Confirm your password', // Confirm Password label
  Email: 'Enter your email',
});



const inter = Inter({ subsets: ["latin"] });
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

const formFields = {
  signIn: {
    username: {
      placeholder: 'Enter your email',
    },
  },
  signUp: {
    given_name: {
      label: 'First Name:',
      placeholder: 'Enter your First Name:',
      isRequired: true,
      order:1,
    },
    family_name: {
      label: 'Last Name:',
      placeholder: 'Enter your Last Name:',
      isRequired: true,
      order:2,
    },
  
    email: {
      label: 'Email:',
      placeholder: 'Enter your Email:',
      isRequired: true,
      order: 3,
    },
    password: {
      label: 'Password:',
      placeholder: 'Enter your Password:',
      isRequired: false,
      order : 4,
    },
    confirm_password: {
      label: 'Confirm Password:',
      order: 5,
    },
  },
  forceNewPassword: {
    password: {
      placeholder: 'Enter your Password:',
    },
  },
  
  confirmResetPassword: {
    confirmation_code: {
      placeholder: 'Enter your Confirmation Code:',
      label: 'Confirmation Code',
      isRequired: false,
    },
    confirm_password: {
      placeholder: 'Enter your Password Please:',
    },
  },
  setupTotp: {
    QR: {
      totpIssuer: 'test issuer',
      totpUsername: 'amplify_qr_test_user',
    },
    confirmation_code: {
      label: 'New Label',
      placeholder: 'Enter your Confirmation Code:',
      isRequired: false,
    },
  },
  confirmSignIn: {
    confirmation_code: {
      label: 'New Label',
      placeholder: 'Enter your Confirmation Code:',
      isRequired: false,
    },
  },
};



const components = {
  Header() {
    const { tokens } = useTheme();

    return (
      <View textAlign="center" padding={tokens.space.zero}>
        <Image
          alt="Learn4Less logo"
          src="./logo.png"
          width="70%"
          height="auto"
          marginTop={tokens.space.xl}
        />
      </View>
    );
  },

  

  Footer() {
    const { tokens } = useTheme();

    return (
      <View textAlign="center" padding={tokens.space.large}>
        <Text color={tokens.colors.neutral[80]}>
          &copy; 2025 Learn4Less Tutoring Services Ltd. All rights reserved.
        </Text>
      </View>
    );
  },

  SignIn: {
    Header() {
      const { tokens } = useTheme();

      return (
        <Heading
          padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
          level={3}
        >
          Sign in to your account
        </Heading>
      );
    },
    Footer() {
      const { toForgotPassword } = useAuthenticator();

      return (
        <View textAlign="center">
          <Button
            fontWeight="normal"
            onClick={toForgotPassword}
            size="small"
            variation="link"
          >
            Reset Password
          </Button>
        </View>
      );
    },
  },

  SignUp: {
    
    Header() {
      const { tokens } = useTheme();

      return (
        <Heading
          padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
          level={3}
        >
          Create a new account
        </Heading>
      );
    },
    Footer() {
      const { toSignIn } = useAuthenticator();

      return (
        <View textAlign="center">
          <Button
            fontWeight="normal"
            onClick={toSignIn}
            size="small"
            variation="link"
          >
            Back to Sign In
          </Button>
        </View>
      );
    },
  },
  ConfirmSignUp: {
    Header() {
      const { tokens } = useTheme();
      return (
        <Heading
          padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
          level={3}
        >
          Enter Information:
        </Heading>
      );
    },
    
  },
  SetupTotp: {
    Header() {
      const { tokens } = useTheme();
      return (
        <Heading
          padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
          level={3}
        >
          Enter Information:
        </Heading>
      );
    },
    
  },
  ConfirmSignIn: {
    Header() {
      const { tokens } = useTheme();
      return (
        <Heading
          padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
          level={3}
        >
          Enter Information:
        </Heading>
      );
    },
    
  },
  ForgotPassword: {
    Header() {
      const { tokens } = useTheme();
      return (
        <Heading
          padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
          level={3}
        >
          Enter Information:
        </Heading>
      );
    },
   
  },
  ConfirmResetPassword: {
    Header() {
      const { tokens } = useTheme();
      return (
        <Heading
          padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
          level={3}
        >
          Enter Information:
        </Heading>
      );
    },
    
  },
};



const LandingPage = ({ onGetStarted }: { onGetStarted: () => void }) => {
  return (
    <View textAlign="center" padding="2rem">
      <Image
        alt="Learn4Less logo" 
        src="./logo.png"
        width="50%"
        height="auto"
      />
      <Heading level={1}>Welcome to Daily Problem App</Heading>
      <Text className="text-2xl">This is a FREE tool for students to have some extra practice problems for Integral Calculus</Text>
      <Text className="pb-4 text-2xl text-red-500 font-bold">For a better experience, use your laptop/tablet</Text>
      <Button className="bg-blue-600 text-white hover:scale-110 text-xl" onClick={onGetStarted}>Get Started</Button>
    </View>
  );
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const [showAuth, setShowAuth] = useState(false);
  const [isMounted, setIsMounted] = useState(false);
  
  // First useEffect to set isMounted to true after component mounts
  useEffect(() => {
    setIsMounted(true);
  }, []);
  
  // Second useEffect that depends on isMounted and runs localStorage checks
  useEffect(() => {
    // Skip if not mounted yet (not client-side)
    if (!isMounted) return;
    
    // Check if we should skip the landing page based on localStorage
    try {
      const lastShown = localStorage.getItem('landingPageLastShown');
      const today = new Date().toDateString();
      
      // Only auto-redirect if we've seen it today
      if (lastShown === today && !showAuth) {
        setShowAuth(true);
      }
    } catch (error) {
      console.error('Error accessing localStorage:', error);
    }
  }, [isMounted, showAuth]);
  
  // Handle the "Get Started" button click
  const handleGetStarted = () => {
    if (typeof window !== 'undefined') {
      try {
        // Save that user has seen the landing page today
        localStorage.setItem('landingPageLastShown', new Date().toDateString());
      } catch (error) {
        console.error('Error saving to localStorage:', error);
      }
    }
    
    setShowAuth(true);
  };
  
  return (
    <html lang="en">
      <head>
        <title>Daily Problems</title>
        <link rel="icon" href="/favicon.ico?v=1" />
        <GoogleAnalytics />
      </head>
      <body>
        {showAuth ? (
          <Authenticator formFields={formFields} components={components}>
            {children}
          </Authenticator>
        ) : (
          <LandingPage onGetStarted={handleGetStarted} />
        )}
      </body>
    </html>
  );
}